services:
  lrs_data_analyst:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    ports:
      - 8100:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../LRSDA:/workspace
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      SIMPLESAMLPHP_CONFIG_DIR: /workspace/simplesamlphp/config
    networks:
      - lrsda-network
  idp_test:
    image: kristophjunge/test-saml-idp
    container_name: idp_test
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=LRS_data_analyst
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:8100/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp
    networks:
      - lrsda-network
networks:
  lrsda-network:
    name: lrsda-network
    driver: bridge