version: '3.9'

services:
  lrs_data_analyst:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    ports:
      - 8100:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../LRSDA:/workspace
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    networks:
      - lrsda-network
  idp_test:
    image: kristophjunge/test-saml-idp
    container_name: idp_test
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=mon-application-super-cool
    networks:
      - lrsda-network
networks:
  lrsda-network:
    name: lrsda-network
    driver: bridge